---
- name: Pull logstash image
  docker_image:
    name: docker.elastic.co/beats/filebeat:8.0.0
    source: pull
- name: Start filebeat container
  docker_container:
    name: filebeat
    image: docker.elastic.co/beats/filebeat:8.0.0
    state: started
    privileged: true
    user: root
    volumes:
      - /home/netology/Projects/elk/roles/filebeat/templates/filebeat.yml:/usr/share/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - name: elastic
        links:
          - logstash
