---
- name: Pull filebeat image
  docker_image:
    name: docker.elastic.co/beats/filebeat:8.0.0
    source: pull
- name: Start filebeat container
  docker_container:
    name: filebeat_tmp
    image: docker.elastic.co/beats/filebeat:8.0.0
    state: started
    command: "--strict.perms=false"
    privileged: true
    user: root
    volumes:
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
- name: Add config file
  command: "docker cp /home/netology/Projects/elk/roles/filebeat/templates/filebeat.yml filebeat_tmp:/usr/share/filebeat/filebeat.yml"
- name: Changed owners
  command: "docker exec -i filebeat_tmp chmod go-w /usr/share/filebeat/filebeat.yml"
- name: New image
  command: "docker commit -m \"Changed config\" -a \"Valeriya Tulyakova\" filebeat_tmp filebeat:my"
- name: New tag
  command: "docker tag filebeat:my elk/filebeat:my"
- name: Stop tmp-container
  command: "docker stop filebeat_tmp"
- name: Start filebeat container
  docker_container:
    name: filebeat
    image: elk/filebeat:my
    state: started
    command: "--strict.perms=false"
    privileged: true
    user: root
    volumes:
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - name: elastic
        links:
          - logstash
- name: Add filebeat in inventory
  add_host:
    name: filebeat
    ansible_connection: docker
