---
- name: Start filebeat container
  docker_container:
    name: filebeat
    image: docker.elastic.co/beats/filebeat:7.16.3
    state: started
    privileged: true
    user: root
    volumes:
      - filebeat.yml.j2:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - logstash
- name: Add filebeat in inventory
  add_host:
    name: filebeat
    ansible_connection: docker

# - name: Configure Filebeat
#   template:
#     src: filebeat.yml.j2
#     dest: /usr/share/filebeat/filebeat.yml
#     mode: 0644