---
- name: Start logstash container
  docker_container:
    name: logstash
    image: docker.elastic.co/logstash/logstash:7.16.3
    volumes:
      - /home/netology/Projects/elk/roles/logstash/templates/config/:/usr/share/logstash/config/
    state: started
    ports:
      - 5046:5046
    links:
      - es-hot
      - es-warm
- name: Add logstash in inventory
  add_host:
    name: logstash
    ansible_connection: docker