---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: filebeat
    image: docker.elastic.co/beats/filebeat:7.16.3
    # privileged: true
    pre_build_image: true
    volumes:
      - /var/lib/docker:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
    network:
      - elastic
    depends_on:
      - logstash
    groups:
      - elk
provisioner:
  name: ansible
  log: true
  options:
    vvv: true
    diff: true
  inventory:
    host_vars:
      filebeat:
        elk_id: 4
verifier:
  name: ansible