---
- name: Start kibana container
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.3
    state: started
    env:
      ELASTICSEARCH_URL: "http://es-hot:9200"
      ELASTICSEARCH_HOSTS: '["http://es-hot:9200","http://es-warm:9200"]'
    ports:
      - 5601:5601
    links:
      - es-hot
      - es-warm
- name: Add kibana in inventory
  add_host:
    name: kibana
    ansible_connection: docker
