---
- name: Start kibana container
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.3
    volumes:
      - kibana.yml.j2:/usr/share/kibana/config/kibana.yml
    state: started
    ports:
      - 5601:5601
    links:
      - es-hot
      - es-warm
- name: Add kibana in inventory
  add_host:
    name: kibana
    ansible_connection: docker
