---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: logstash
    image: docker.elastic.co/logstash/logstash:7.16.3
    pre_build_image: true
    ports:
      - 5046:5046
    network:
      - elastic
    depends_on:
      - es-hot
      - es-warm
    groups:
      - elk
provisioner:
  name: ansible
  log: true
  options:
    vvv: true
    diff: true
  inventory:
    host_vars:
      logstash:
        elk_id: 3
verifier:
  name: ansible