---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.3
    pre_build_image: true
    ports:
      - 5601:5601
    network:
      - elastic
    depends_on:
      - es-hot
      - es-warm
    groups:
      - elk
provisioner:
  name: ansible
  log: true
  options:
    vvv: true
    diff: true
  inventory:
    host_vars:
      kibana:
        elk_id: 2
verifier:
  name: ansible