---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: es-hot
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    pre_build_image: true
    volumes:
      - data01:/usr/share/elasticsearch/data
    # ulimits:
    #   memlock:
    #     soft: "-1"
    #     hard: "-1"
    #   nofile:
    #     soft: "65536"
    #     hard: "65536"
    ports:
      - 9200:9200
    network:
      - elastic
    depends_on:
      - es-warm
    groups:
      - elk
  - name: es-warm
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    pre_build_image: true
    volumes:
      - data02:/usr/share/elasticsearch/data
    # ulimits:
    #   memlock:
    #     soft: "-1"
    #     hard: "-1"
    #   nofile:
    #     soft: "65536"
    #     hard: "65536"
    network:
      - elastic
    groups:
      - elk
provisioner:
  name: ansible
  log: true
  options:
    vvv: true
    diff: true
  inventory:
    host_vars:
      es-hot:
        elk_id: 0
      es-warm:
        elk_id: 1

verifier:
  name: ansible
