---
- name: Pull elastic image
  docker_image:
    name: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    source: pull
- name: Copy files for config
  copy:
    src: ./templates/warm
    dest: /t1/
- name: Start es-warm container
  docker_container:
    name: es-warm
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    state: started
    volumes:
      - /t1:/usr/share/elasticsearch/config/
      - data02:/usr/share/elasticsearch/data
    ulimits:
      - memlock:-1:-1
      - nofile:262144:262144
- name: Add es-warm in inventory
  add_host:
    name: es-warm
    ansible_connection: docker
- name: Start es-hot container
  docker_container:
    name: es-hot
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    state: started
    volumes:
      - elasticsearch.yml.j2:/usr/share/elasticsearch/config/elasticsearch.yml
      - data01:/usr/share/elasticsearch/data
    ulimits:
      - memlock:-1:-1
      - nofile:262144:262144
    ports:
      - 9200:9200
    links:
      - es-warm
- name: Add es-hot in inventory
  add_host:
    name: es-hot
    ansible_connection: docker
# - name: Check for Python
#   raw: test -e /usr/bin/python
#   changed_when: false
#   failed_when: false
#   register: check_python
# - name: Install Python
#   raw: apt -y update && apt install -y python
#   when: check_python.rc != 0