---
- name: Work with elasticsearch-role (warm)
  docker_container:
    name: es-warm
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    volumes:
      - data02:/usr/share/elasticsearch/data
    # ulimits:
    #   memlock: -1:-1
    #   nofile: 65536:65536
    # networks:
    #   - elastic
- name: Add es-warm in inventory
  add_host:
    name: es-warm
    ansible_connection: docker
- name: Work with elasticsearch-role (hot)
  docker_container:
    name: es-hot
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    volumes:
      - data01:/usr/share/elasticsearch/data
    ulimits:
      memlock: -1:-1
      nofile: 65536:65536
    ports:
      - 9200:9200
    networks:
      - elastic
    links:
      - es-warm
- name: Add es-hot in inventory
  add_host:
    name: es-hot
    ansible_connection: docker

- name: Work with kibana-role
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - 5601:5601
    networks:
      - elastic
    links:
      - es-hot
      - es-warm
- name: Add kibana in inventory
  add_host:
    name: kibana
    ansible_connection: docker

- name: Work with logstash-role
  docker_container:
    name: logstash
    image: docker.elastic.co/logstash/logstash:7.16.3
    ports:
      - 5046:5046
    networks:
      - elastic
    links:
      - es-hot
      - es-warm
- name: Add logstash in inventory
  add_host:
    name: logstash
    ansible_connection: docker
- name: Work with filebeat-role
  docker_container:
    name: filebeat
    image: docker.elastic.co/beats/filebeat:7.16.3
    privileged: true
    user: root
    volumes:
      - /var/lib/docker:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
    network:
      - elastic
    depends_on:
      - logstash
- name: Add filebeat in inventory
  add_host:
    name: filebeat
    ansible_connection: docker
